# Generated by Django 2.1.7 on 2019-06-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpair',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.Product'),
        ),
    ]
