# Generated by Django 2.1.7 on 2019-06-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0002_auto_20190623_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_products', models.ManyToManyField(to='MyShop.ProductPair')),
            ],
        ),
    ]
