# Generated by Django 2.1.7 on 2019-06-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0002_auto_20190624_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='usern',
        ),
    ]
