# Generated by Django 2.1.7 on 2019-06-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAccounts', '0002_auto_20190622_1248'),
        ('MyShop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='MyAccounts.UserProfile'),
            preserve_default=False,
        ),
    ]
