# Generated by Django 2.1.7 on 2019-06-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, to='MyAccounts.UserProfile'),
        ),
    ]
