# Generated by Django 2.1.7 on 2019-06-22 12:48

import MyAccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.IntegerField(validators=[MyAccounts.models.UserProfile.check_phoneno]),
        ),
    ]
